name: CI
on:
  pull_request:
  push:
    branches: [main, 'release-*']
    tags: ['v*']

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.26.x
      - run: make check_license
      - run: make style
      - run: make -C assets style
      - run: make check-go-mod-version

  test-assets:
    name: Test Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.26.x
      - run: make -C assets test

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      # Override Go 1.18 security deprecations.
      GODEBUG: "x509sha1=1,tls10default=1"
    strategy:
      matrix:
        go:
          - 1.25.x
          - 1.26.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: ${{ matrix.go }}
      - run: make test
